spring.application.name=parent

erp.finance.api.db.hostName=localhost
erp.finance.api.db.port=5432
erp.finance.api.db.databaseName=erp-system-db
erp.finance.api.db.schemaName=rm_material_schema
erp.finance.api.db.username=postgres
erp.finance.api.db.password=s5r5i5GT
erp.finance.api.db.connectionpoolInitialSize=10
erp.finance.api.db.connectionpoolMaxSize=20
erp.finance.api.db.connectionpoolMaxWaitTime=1000
erp.finance.api.db.connectionpoolMaxIdleTime=3000
erp.finance.api.db.connectionpoolMaxLifetime=18000

server.error.include-message=always
server.error.include-binding-errors=always
server.error.include-stacktrace=always

logging.level.com.hst.erp=DEBUG
logging.level.org.springframework.r2dbc=DEBUG
logging.level.io.r2dbc=DEBUG

